/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
/** biome-ignore-all lint/style/useConst: <explanation> */
/** biome-ignore-all lint/suspicious/noAssignInExpressions: <explanation> */

import AlienRPGActiveEffect from "../documents/active-effect.mjs"
import { addSign } from "../helpers/utils.mjs"
// import { ALIENRPG } from '../helpers/config.js';
import { yze } from "../helpers/YZEDiceRoller.mjs"

export class alienrpgActor extends Actor {
	/** @override */
	prepareData() {
		// Prepare data for the actor. Calling the super version of this executes
		// the following, in order: data reset (to clear active effects),
		// prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
		// prepareDerivedData().
		super.prepareData()
		switch (this.type) {
			case "territory":
				this.img = "systems/alienrpg/images/icons/nested-eclipses.webp"
				break
			case "colony":
				this.img = "systems/alienrpg/images/icons/digital-trace.webp"
				break
			case "planet":
				this.img = "systems/alienrpg/images/icons/double-ringed-orb.webp"
				break

			default:
				break
		}
	}

	/** @override */
	prepareBaseData() {
		// Data modifications in this step occur before processing embedded
		// documents or derived data.
	}

	/**
	 * @override
	 * Augment the actor source data with additional dynamic data that isn't
	 * handled by the actor's DataModel. Data calculated in this step should be
	 * available both inside and outside of character sheets (such as if an actor
	 * is queried and has a roll executed directly from it).
	 */
	prepareDerivedData() {
		const flags = this.flags.ALIENRPG || {}
	}

	/**
	 *
	 * @override
	 * Augment the actor's default getRollData() method by appending the data object
	 * generated by the its DataModel's getRollData(), or null. This polymorphic
	 * approach is useful when you have actors & items that share a parent Document,
	 * but have slightly different data preparation needs.
	 */
	getRollData() {
		return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) }
	}
	// *************************************************
	// Setupthe prototype token
	// *************************************************

	async _preCreate(context, options, user) {
		await super._preCreate(context, options, user)
		const tokenProto = {
			"prototypeToken.displayName": CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
			"prototypeToken.displayBars": CONST.TOKEN_DISPLAY_MODES.OWNER_HOVER,
			"prototypeToken.disposition": CONST.TOKEN_DISPOSITIONS.FRIENDLY,
			"prototypeToken.name": `${context.name}`,
			"prototypeToken.bar1": { attribute: "header.health" },
			"prototypeToken.bar2": { attribute: "None" },
			// 'prototypeToken.vision': true,
			"prototypeToken.actorLink": true,
			"prototypeToken.sight.enabled": "true",
			"prototypeToken.sight.range": "12",
		}
		if (game.settings.get("alienrpg", "defaultTokenSettings")) {
			switch (context.type) {
				case "character":
					tokenProto["prototypeToken.bar2"] = { attribute: "header.stress" }
					break
				case "vehicles":
					tokenProto["prototypeToken.bar1"] = { attribute: "None" }
					break
				case "creature":
					tokenProto["prototypeToken.actorLink"] = false
					tokenProto["prototypeToken.disposition"] = CONST.TOKEN_DISPOSITIONS.HOSTILE
					tokenProto["prototypeToken.sight.enabled"] = false
					break
				case "synthetic":
					break
				case "territory":
					tokenProto["prototypeToken.bar1"] = { attribute: "None" }
					tokenProto["prototypeToken.img"] = "systems/alienrpg/images/icons/nested-eclipses.svg"
					tokenProto["prototypeToken.texture.src"] = "systems/alienrpg/images/icons/nested-eclipses.webp"
					tokenProto["prototypeToken.sight.enabled"] = false
					break
				case "spacecraft":
					tokenProto["prototypeToken.bar1"] = {
						attribute: "attributes.damage",
					}
					break
				case "colony":
					tokenProto["prototypeToken.bar1"] = { attribute: "None" }
					tokenProto["prototypeToken.img"] = "systems/alienrpg/images/icons/digital-trace.webp"
					tokenProto["prototypeToken.texture.src"] = "systems/alienrpg/images/icons/digital-trace.webp"
					tokenProto["prototypeToken.disposition"] = CONST.TOKEN_DISPOSITIONS.NEUTRAL
					tokenProto["prototypeToken.sight.enabled"] = false
					break
				case "planet":
					tokenProto["prototypeToken.bar1"] = { attribute: "None" }
					tokenProto["prototypeToken.img"] = "systems/alienrpg/images/icons/double-ringed-orb.webp"
					tokenProto["prototypeToken.texture.src"] = "systems/alienrpg/images/icons/double-ringed-orb.webp"
					tokenProto["prototypeToken.disposition"] = CONST.TOKEN_DISPOSITIONS.NEUTRAL
					tokenProto["prototypeToken.sight.enabled"] = false
					break
			}
		}

		this.updateSource(tokenProto)
		// this.updateSource(createData);
	}
	async checkOverwatch(context) {
		const conDition = await this.hasCondition("overwatch")
		if (conDition !== undefined || conDition) {
			foundry.utils.setProperty(context, "system.general.overwatch", true)
		} else {
			foundry.utils.setProperty(context, "system.general.overwatch", false)
		}

		const conDition2 = await this.hasCondition("starving")
		if (conDition2 !== undefined || conDition2) {
			foundry.utils.setProperty(context, "system.general.starving", true)
		} else {
			foundry.utils.setProperty(context, "system.general.starving", false)
		}
		const conDition3 = await this.hasCondition("dehydrated")
		if (conDition3 !== undefined || conDition3) {
			foundry.utils.setProperty(context, "system.general.dehydrated", true)
		} else {
			foundry.utils.setProperty(context, "system.general.dehydrated", false)
		}
		const conDition4 = await this.hasCondition("exhausted")
		if (conDition4 !== undefined || conDition4) {
			foundry.utils.setProperty(context, "system.general.exhausted", true)
		} else {
			foundry.utils.setProperty(context, "system.general.exhausted", false)
		}
		const conDition5 = await this.hasCondition("freezing")
		if (conDition5 !== undefined || conDition5) {
			foundry.utils.setProperty(context, "system.general.freezing", true)
		} else {
			foundry.utils.setProperty(context, "system.general.freezing", false)
		}
		const conDition6 = await this.hasCondition("panicked")
		if (conDition6 !== undefined || conDition6) {
			foundry.utils.setProperty(context, "system.general.panic.value", 1)
		} else {
			foundry.utils.setProperty(context, "system.general.panic.value", 0)
		}
		const conDition7 = await this.hasCondition("hypoxia")
		if (conDition7 !== undefined || conDition7) {
			foundry.utils.setProperty(context, "system.general.hypoxia", true)
		} else {
			foundry.utils.setProperty(context, "system.general.hypoxia", false)
		}
		const conDition8 = await this.hasCondition("heatstroke")
		if (conDition8 !== undefined || conDition8) {
			foundry.utils.setProperty(context, "system.general.heatstroke", true)
		} else {
			foundry.utils.setProperty(context, "system.general.heatstroke", false)
		}
		const conDition9 = await this.hasCondition("gravitydyspraxia")
		if (conDition9 !== undefined || conDition9) {
			foundry.utils.setProperty(context, "system.general.gravitydyspraxia", true)
		} else {
			foundry.utils.setProperty(context, "system.general.gravitydyspraxia", false)
		}
	}
	async abilityRoll(actor, dataset, rollMod) {
		const config = CONFIG.ALIENRPG
		let label = dataset.label
		let r2Data = 0
		let reRoll = false
		let actorId = actor.id
		let effectiveActorType = actor.type
		const attrib = dataset.attr
		const blind = false
		game.alienrpg.rollArr.sCount = 4
		game.alienrpg.rollArr.multiPush = 0
		const modifier = Number(dataset?.mod ?? 0) + Number(dataset?.modifier ?? 0)
		const stressMod = Number(dataset?.stressMod ?? 0)
		let response = ""
		let content = ""
		let title = ""

		// the dataset value is returned to the DOM so it should be set to 0 in case a future roll is made without the
		// modifier dialog.

		dataset.modifier = 0
		dataset.stressMod = 0

		if (dataset.roll) {
			let r1Data = Number(dataset.roll || 0) + Number(modifier || 0)
			if (dataset.attr) {
				r1Data = Number(modifier || 0)
			}

			reRoll = true
			r2Data = 0

			switch (actor.type) {
				case "character":
					reRoll = false
					r2Data =
						actor.getRollData().header.stress.value +
						Number(actor.getRollData().header.stress.mod || 0) +
						Number(stressMod)
					break
				case "synthetic":
					if (actor.system.header.synthstress) {
						effectiveActorType = "character" // make rolls look human
						r2Data = Number(stressMod)
						reRoll = false
					}
					break

				case "vehicles":
				case "spacecraft":
					if (dataset.spbutt !== "armor") {
						actorId = dataset.actorid
						const pilotData = game.actors.get(dataset.actorid)
						if (pilotData.type === "synthetic") {
							r2Data = 0
							reRoll = true
						} else {
							r2Data = pilotData.getRollData().header.stress.value + Number(stressMod) || 0
							reRoll = false
						}
					}
					break

				default:
					break
			}

			if (dataset.spbutt === "armor") {
				if (r1Data < 1 && !dataset.armorP && !dataset.armorDou) {
					return
				}
				label = game.i18n.localize("ALIENRPG.Armor")
				r2Data = 0
				reRoll = true

				if (dataset.armorP === "true" && game.settings.get("alienrpg", "evolved")) {
					r1Data = Number(r1Data - 1 || 0) // fix to armor so it rounds up instead of down
					dataset.armorP = "false"
				} else {
					if (dataset.armorP === "true") {
						r1Data = Number(Math.ceil(r1Data / 2)) // fix to armor so it rounds up instead of down
						dataset.armorP = "false"
					}
				}
				if (dataset.armorDou === "true") {
					r1Data = Number(r1Data * 2)
					dataset.armorDou = "false"
				}
			}
			if (label === game.i18n.localize("ALIENRPG.Radiation")) {
				r2Data = 0
				reRoll = true
				r1Data += 1
			}

			if (attrib && actor.type !== "synthetic" && !rollMod) {
				reRoll = false
				title =
					game.i18n.localize("ALIENRPG.Attributes") +
					" " +
					dataset.label +
					" " +
					game.i18n.localize("ALIENRPG.DialTitle2")
				content = await foundry.applications.handlebars.renderTemplate(
					"systems/alienrpg/templates/dialog/roll-attr-dialog.hbs",
					actor,
					dataset,
				)
				response = await foundry.applications.api.DialogV2.wait({
					window: { title: title },
					content,
					rejectClose: false,
					buttons: [
						{
							label: "ALIENRPG.DialRoll",
							callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
						},
						{
							label: "ALIENRPG.DialCancel",
							action: "cancel",
						},
					],
				})

				if (!response || response === "cancel") return "cancelled"
				if (response) {
					if (!response.rollStress) {
						r2Data = 0
						reRoll = true
					}
					yze.yzeRoll(
						effectiveActorType,
						blind,
						reRoll,
						label,
						r1Data,
						game.i18n.localize("ALIENRPG.Black"),
						r2Data,
						game.i18n.localize("ALIENRPG.Yellow"),
						actorId,
					)
					game.alienrpg.rollArr.sCount = game.alienrpg.rollArr.r1Six + game.alienrpg.rollArr.r2Six
				}
			} else if (actor.type === "spacecraft" && dataset.spbutt === "comtech") {
				content = await foundry.applications.handlebars.renderTemplate(
					"systems/alienrpg/templates/dialog/roll-space-comtech.hbs",
					{ config, actor, dataset },
				)
				response = await foundry.applications.api.DialogV2.wait({
					window: { title: title },
					content,
					rejectClose: false,
					buttons: [
						{
							label: "ALIENRPG.DialRoll",
							callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
						},
						{
							label: "ALIENRPG.DialCancel",
							action: "cancel",
						},
					],
				})

				if (!response || response === "cancel") return "cancelled"
				if (response) {
					let baseModifier = Number(response.baseModifier)
					let stressMod = Number(response.stressMod)
					let modifier = Number(response.sigMod)
					let targetLock = Number(response.targetLock)
					let targetMod = Number(response.targetMod)
					r1Data = r1Data + baseModifier + modifier + targetLock + targetMod
					r2Data = r2Data + stressMod
					yze.yzeRoll(
						effectiveActorType,
						blind,
						reRoll,
						label,
						r1Data,
						game.i18n.localize("ALIENRPG.Black"),
						r2Data,
						game.i18n.localize("ALIENRPG.Yellow"),
						actorId,
					)
					game.alienrpg.rollArr.sCount = game.alienrpg.rollArr.r1Six + game.alienrpg.rollArr.r2Six
				}
			} else {
				yze.yzeRoll(
					effectiveActorType,
					blind,
					reRoll,
					label,
					r1Data,
					game.i18n.localize("ALIENRPG.Black"),
					r2Data,
					game.i18n.localize("ALIENRPG.Yellow"),
					actorId,
				)
				game.alienrpg.rollArr.sCount = game.alienrpg.rollArr.r1Six + game.alienrpg.rollArr.r2Six
			}
		}
	}

	async rollAbilityMod(actor, dataset) {
		const config = CONFIG.ALIENRPG
		let content = ""
		let response = ""
		const title =
			game.i18n.localize("ALIENRPG.DialTitle1") + " " + dataset.label + " " + game.i18n.localize("ALIENRPG.DialTitle2")
		let stressMod = 0
		let modifier = 0
		const confirmed = false
		let armorP = false
		let armorDou = false

		if (dataset.roll) {
			// call pop up box here to get any mods then use standard RollAbility()
			// Check that is a character (and not armor) or a synth pretending to be a character.
			if (
				((actor.type === "character" || actor.type === "vehicles" || actor.type === "spacecraft") &&
					dataset.spbutt !== "armor") ||
				actor.system.header.synthstress
			) {
				content = await foundry.applications.handlebars.renderTemplate(
					"systems/alienrpg/templates/dialog/roll-all-dialog.hbs",
					actor,
					dataset.dataset,
				)
			} else if (actor.type === "synthetic") {
				content = await foundry.applications.handlebars.renderTemplate(
					"systems/alienrpg/templates/dialog/roll-base-dialog.hbs",
					actor,
					dataset.dataset,
				)
			} else {
				content = await foundry.applications.handlebars.renderTemplate(
					"systems/alienrpg/templates/dialog/roll-base-dialog.hbs",
					actor,
					dataset.dataset,
				)
			}
		}

		switch (dataset.spbutt) {
			case "armorVfire":
				{
					response = await foundry.applications.api.DialogV2.wait({
						window: { title: title },
						content,
						rejectClose: false,
						buttons: [
							{
								label: "ALIENRPG.DialRoll",
								callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
							},
							{
								label: "ALIENRPG.DialCancel",
								action: "cancel",
							},
						],
					})

					if (!response || response === "cancel") return "cancelled"
					if (response) {
						if (!response.stressMod) {
							stressMod = 0
						} else stressMod = Number(response.stressMod)
						if (response.modifier === "undefined") {
							modifier = 0
						} else modifier = Number(response.modifier)
						if (Number.isNaN(response.modifier)) modifier = 0
						if (Number.isNaN(response.stressMod)) stressMod = 0

						dataset.modifier = modifier
						dataset.stressMod = stressMod
						this.abilityRoll(actor, dataset, confirmed)
					}
				}
				break
			case "armor":
				{
					if (game.settings.get("alienrpg", "evolved")) {
						response = await foundry.applications.api.DialogV2.wait({
							window: { title: title },
							content,
							rejectClose: false,
							buttons: [
								{
									action: "AP",
									label: "ALIENRPG.ArmorPiercing",
									callback: () => (armorP = true),
								},
								{
									label: "ALIENRPG.DialRoll",
									callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
								},
								{
									label: "ALIENRPG.DialCancel",
									action: "cancel",
								},
							],
						})
					} else {
						response = await foundry.applications.api.DialogV2.wait({
							window: { title: title },
							content,
							rejectClose: false,
							buttons: [
								{
									action: "AP",
									label: "ALIENRPG.ArmorPiercing",
									callback: () => (armorP = true),
								},
								{
									action: "AD",
									label: "ALIENRPG.ArmorDoubled",
									callback: () => (armorDou = true),
								},
								{
									label: "ALIENRPG.DialRoll",
									callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
								},
								{
									label: "ALIENRPG.DialCancel",
									action: "cancel",
								},
							],
						})
					}
					if (!response || response === "cancel") return "cancelled"

					if (response || armorP || armorDou) {
						if (!response.stressMod) {
							stressMod = 0
						} else stressMod = Number(response.stressMod)
						if (response.modifier === "undefined") {
							modifier = 0
						} else modifier = Number(response.modifier)
						if (Number.isNaN(response.modifier)) modifier = 0
						if (Number.isNaN(response.stressMod)) stressMod = 0

						dataset.modifier = modifier
						dataset.stressMod = stressMod
						dataset.armorP = armorP
						dataset.armorDou = armorDou
						this.abilityRoll(actor, dataset, confirmed)
					}
				}
				break
			default:
				{
					response = await foundry.applications.api.DialogV2.wait({
						window: { title: title },
						content,
						rejectClose: false,
						buttons: [
							{
								label: "ALIENRPG.DialRoll",
								callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
							},
							{
								label: "ALIENRPG.DialCancel",
								action: "cancel",
							},
						],
					})

					if (!response || response === "cancel") return "cancelled"
					if (response) {
						if (!response.stressMod) {
							stressMod = 0
						} else stressMod = Number(response.stressMod)
						if (response.modifier === "undefined") {
							modifier = 0
						} else modifier = Number(response.modifier)
						if (Number.isNaN(response.modifier)) modifier = 0
						if (Number.isNaN(response.stressMod)) stressMod = 0

						dataset.modifier = modifier
						dataset.stressMod = stressMod

						this.abilityRoll(actor, dataset, confirmed)
					}
				}
				break
		}
	}
	async rollPanic(actor, dataset) {
		const config = CONFIG.ALIENRPG
		const actorId = actor.id
		let blind = false
		let oldPanic = 0
		const modifier = Number(dataset?.mod ?? 0) + Number(dataset?.modifier ?? 0)
		const stressMod = Number(dataset?.stressMod ?? 0)

		let chatMessage = ""
		const table = game.tables.getName("Panic Table")
		if (!table) {
			return ui.notifications.error(game.i18n.localize("ALIENRPG.NoPanicTable"))
		}

		const rollModifier = Number(modifier) + Number(stressMod)

		let aStress = 0

		if (actor.type === "synthetic") {
			if (!actor.system.header.synthstress) return

			aStress = 0
		} else aStress = actor.getRollData().header.stress.value + rollModifier

		const modRoll = "1d6" + "+" + Number(aStress)
		const roll = await new Roll(modRoll).evaluate()
		const customResults = await table.roll({ roll })
		console.warn(
			`Rolling stress, ${modRoll}, Panic Value ${actor.system.general.panic.value}, Last ${actor.system.general.panic.lastRoll}, Roll ${customResults.roll.total}`,
		)

		oldPanic = actor.system.general.panic.lastRoll

		if (customResults.roll.total >= 7 && actor.system.general.panic.value === 0) {
			await actor.update({ "system.general.panic.value": 1 })
			await this.causePanic(actor)
		}

		chatMessage +=
			'<h2 class="alienchatred ctooltip">' +
			game.i18n.localize("ALIENRPG.PanicCondition") +
			" " +
			addSign(aStress).toString() +
			'<span class="ctooltiptext">' +
			game.i18n.localize("ALIENRPG.Stress") +
			" + (" +
			(actor.getRollData().header.stress.value || 0) +
			") <br>+ " +
			game.i18n.localize("ALIENRPG.StressMod") +
			" + (" +
			stressMod +
			") <br>+ " +
			game.i18n.localize("ALIENRPG.Talent-Crit") +
			" + (" +
			modifier +
			")" +
			"</span></h2>"

		const mPanic = customResults.roll.total < actor.system.general.panic.lastRoll
		let pCheck = oldPanic + 1
		console.warn(`More Panic, ${mPanic}, pCheck Value ${pCheck}, old Panic Value ${oldPanic}`)
		if (mPanic && actor.system.general.panic.value === 1) {
			await actor.update({ "system.general.panic.lastRoll": pCheck })

			chatMessage +=
				'<h4 style="font-weight: bolder"><i><b>' +
				game.i18n.localize("ALIENRPG.Roll") +
				" " +
				`${customResults.roll.total}` +
				" " +
				'<span class="alienchatred"><i><b>' +
				game.i18n.localize("ALIENRPG.MorePanic") +
				"</span></b></i></span></h4>"

			chatMessage +=
				"<h4><i>" +
				game.i18n.localize("ALIENRPG.PCPanicLevel") +
				'<b class="alienchatred">' +
				game.i18n.localize("ALIENRPG.Level") +
				" " +
				`${pCheck}` +
				" " +
				game.i18n.localize("ALIENRPG.Seepage104") +
				"</b></i></h4>"

			chatMessage += await this.morePanic(pCheck)
		} else {
			if (actor.type === "character")
				await actor.update({
					"system.general.panic.lastRoll": customResults.roll.total,
				})
			pCheck = customResults.roll.total
			chatMessage += "<h4><i><b>" + game.i18n.localize("ALIENRPG.Roll") + " " + `${pCheck}` + " </b></i></h4>"
			// chatMessage += game.i18n.localize(`ALIENRPG.${customResults.results[0].text}`);
			chatMessage += await this.morePanic(pCheck)
			if (customResults.roll.total >= 7) {
				chatMessage +=
					`<h4 class="alienchatred"><i><b>` +
					game.i18n.localize("ALIENRPG.YouAreAtPanic") +
					// ` <b>` +
					game.i18n.localize("ALIENRPG.Level") +
					` ${pCheck}</b></i></h4>`
			}
		}
		const trauma = customResults.roll.total >= 13 || pCheck >= 13
		if (trauma) {
			chatMessage +=
				"<h4><b>" +
				game.i18n.localize("ALIENRPG.PermanantTrauma") +
				"<i>(" +
				game.i18n.localize("ALIENRPG.Seepage106") +
				") </i></b></h4>"
		}
		if (customResults.roll.total >= 10) {
			chatMessage += `<img src="systems/alienrpg/images/icons/warning-bar.webp" > `
			chatMessage +=
				`<h4 class="alienchatred" style="font-weight: bolder; margin-bottom: auto; margin-left:10px;"><b>` +
				game.i18n.localize("ALIENRPG.ActionFailed") +
				" " +
				customResults.roll.total +
				"</b></h4>"
			chatMessage += `<img src="systems/alienrpg/images/icons/warning-bar.webp"> `
		}

		const rollMode = game.settings.get("core", "rollMode")
		let whispertarget = []

		if (rollMode === "gmroll" || rollMode === "blindroll") {
			whispertarget = game.users.contents.filter((u) => u.isGM).map((u) => u._id)
		} else if (rollMode === "selfroll") {
			whispertarget = game.users.contents.filter((u) => u.isGM).map((u) => u._id)
			whispertarget.push(game.user._id)
		}

		blind = false
		if (rollMode === "blindroll") {
			blind = true
			if (!game.user.isGM) {
				function SelfMessage(content, sound) {
					const selftarget = []
					selftarget.push(game.user._id)

					ChatMessage.create({
						speaker: { actor: actorId },
						content,
						whisper: selftarget,
						type: CONST.CHAT_MESSAGE_STYLES.OTHER,
						sound,
						blind: false,
					})
				}

				SelfMessage(
					'<h2 class="alienchatred">' +
						game.i18n.localize("ALIENRPG.PanicCondition") +
						addSign(aStress).toString() +
						" ???</h2>",
					CONFIG.sounds.dice,
				)
			}
		}
		switch (pCheck) {
			case 7:
			case 9:
			case 10:
				{
					// increase
					await actor.update({
						"system.header.stress.value": actor.system.header.stress.value + 1,
					})
				}
				break

			case 8:
				// Agility -2
				{
					const agilityModName =
						game.i18n.localize("ALIENRPG.PanicCondition") + " - " + game.i18n.localize("ALIENRPG.AbilityAgl") + " -2"
					// const agilityMod = actor.items.getName(agilityModName);
					if (!actor.items.getName(agilityModName)) {
						const rollData = {
							type: "item",
							img: "systems/alienrpg/images/panic.webp",
							name: agilityModName,
							"system.header.type.value": 5,
							"system.attributes.comment.value": game.i18n.localize("ALIENRPG.Panic8"),
							"system.modifiers.attributes.agl.value": -2,
							"system.header.active": "true",
						}
						await this.createEmbeddedDocuments("Item", [rollData])
					}
				}
				break

			case 11:
			case 12:
			case 13:
				{
					//decrease
					await actor.update({
						"system.header.stress.value": actor.system.header.stress.value - 1,
					})
				}
				break

			default:
				break
		}

		const chatData = {
			user: game.user.id,
			speaker: ChatMessage.getSpeaker({
				actor: actor.id,
			}),
			content: chatMessage,
			whisper: whispertarget,
			rolls: customResults.roll,
			sound: CONFIG.sounds.dice,
		}
		if (["gmroll", "blindroll"].includes(chatData.rollMode)) {
			chatData.whisper = ChatMessage.getWhisperRecipients("GM")
		} else if (chatData.rollMode === "selfroll") {
			chatData.whisper = [game.user]
		}
		ChatMessage.create(chatData)
	}
	async rollPanicMod(actor, dataset) {
		const config = CONFIG.ALIENRPG
		const content = await foundry.applications.handlebars.renderTemplate(
			"systems/alienrpg/templates/dialog/roll-stress-dialog.hbs",
			actor,
			dataset.dataset,
		)
		let response = ""
		const title =
			game.i18n.localize("ALIENRPG.DialTitle1") + " " + dataset.label + " " + game.i18n.localize("ALIENRPG.DialTitle2")
		let stressMod = 0
		response = await foundry.applications.api.DialogV2.wait({
			window: { title: title },
			content,
			rejectClose: false,
			buttons: [
				{
					label: "ALIENRPG.DialRoll",
					callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
				},
				{
					label: "ALIENRPG.DialCancel",
					action: "cancel",
				},
			],
		})

		if (!response || response === "cancel") return "cancelled"
		if (response) {
			if (!response.stressMod) {
				stressMod = 0
			} else stressMod = Number(response.stressMod)
			if (Number.isNaN(response.stressMod)) stressMod = 0

			dataset.stressMod = stressMod

			this.rollPanic(actor, dataset)
		}
	}
	async morePanic(pCheck) {
		let con = ""
		switch (pCheck) {
			case 1:
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
				con = game.i18n.localize("ALIENRPG.Panic1")
				break
			case 7:
				con = game.i18n.localize("ALIENRPG.Panic7")
				break
			case 8:
				con = game.i18n.localize("ALIENRPG.Panic8")
				break
			case 9:
				con = game.i18n.localize("ALIENRPG.Panic9")
				break
			case 10:
				con = game.i18n.localize("ALIENRPG.Panic10")
				break
			case 11:
				con = game.i18n.localize("ALIENRPG.Panic11")
				break
			case 12:
				con = game.i18n.localize("ALIENRPG.Panic12")
				break
			case 13:
				con = game.i18n.localize("ALIENRPG.Panic13")
				break
			case 14:
				con = game.i18n.localize("ALIENRPG.Panic14")
				break
			default:
				con = game.i18n.localize("ALIENRPG.Panic15")
				break
		}
		return con
	}
	async rollResolve(actor, dataset) {
		const config = CONFIG.ALIENRPG
		let htmlData = ""
		let aStress = 0
	const oldStress = actor.getRollData().general.stressresponse.value

		const resolve = actor.getRollData().header.resolve.value
		const modifier = Number(dataset?.mod ?? 0) + Number(dataset?.modifier ?? 0)
		const resolveMod = Number(dataset?.resolveMod ?? 0)
		const table = game.tables.getName("Stress Response Table")
		let status = ""
		let effectid = ""
		if (!table) {
			return ui.notifications.error(game.i18n.localize("ALIENRPG.NoResolveTable"))
		}

		const resolveModifier = Number(resolve) + Number(resolveMod)

		if (actor.type === "synthetic") {
			if (!actor.system.header.synthstress) return
			aStress = 0
		} else {
			aStress = actor.getRollData().header.stress.value
		}
		const  roll = await new Roll(`(1d6)`).evaluate()
		let rollTotal = roll.total + (aStress - resolveModifier)
		console.warn(
			`Rolling Resolve, ${roll}, Dice Value, ${roll.total}, Resolve Value ${aStress}, Current level ${oldStress}, Total Roll ${rollTotal}`,
		)
		if (rollTotal <= oldStress) {
			console.log("you already have condition =>: ", rollTotal, "existing level: ", oldStress)
			rollTotal = oldStress + 1
		}
				if (rollTotal < 0) {
			console.log("Can't go Lower than 0")
			rollTotal = 0
		} else {
			if (rollTotal >= 7 || oldStress >= 7) {
				console.log("Can't go heigher than 7")
				rollTotal = 7
			}
		}
		const customResults = await table.getResultsForRoll(rollTotal)
		let altDescription = customResults[0].description

		switch (rollTotal) {
			case 0:
				break
			case 1:
				{
					effectid = "jumpy"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						if (await this.hasCondition("deflated")) {
							altDescription = game.i18n.localize("ALIENRPG.CantGetJumpy")
						} else {
							status = effectid
						}
					}
				}
				break
			case 2:
				{
					effectid = "tunnelvision"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						status = effectid
					}
				}
				break
			case 3:
				{
					effectid = "aggravated"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						status = effectid
					}
				}
				break
			case 4:
				{
					effectid = "shakes"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						status = effectid
					}
				}
				break
			case 5:
				{
					effectid = "frantic"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						status = effectid
					}
				}
				break
			case 6:
				{
					effectid = "deflated"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						if (await this.hasCondition("jumpy")) {
							await this.toggleStatusEffect("jumpy")
						}
						status = effectid
					}
				}
				break
			case 7:
				{
					effectid = "messup"
					if (await this.hasCondition(effectid)) {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						altDescription = game.i18n.localize("ALIENRPG.YouAlreadyHaveThis")
					} else {
						status = effectid 
					}
				}
				break
			default:
				// {
				// 	const addPanic = actor.getRollData().general.addpanic.value
				// 	await actor.update({
				// 		"system.header.stress.value": actor.system.header.stress.value + addPanic,
				// 	})
				// }
				break
		}

		if (status) {
			await this.toggleStatusEffect(status)
			await actor.update({
			"system.general.stressresponse.value": rollTotal,
		})	
	}

		htmlData = {
			actorname: actor.name,
			img: customResults[0].img,
			name: customResults[0].name,
			description: altDescription,
			resolve: resolve,
			modifier: resolveModifier,
			result: rollTotal,
		}

		const html = await foundry.applications.handlebars.renderTemplate(
			"systems/alienrpg/templates/chat/stress-response-roll.hbs",
			htmlData,
		)
		const chatData = {
			user: game.user.id,
			speaker: {
				actor: actor.id,
			},
			content: html,
			other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
			sound: CONFIG.sounds.dice,
		}

		ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"))
		return ChatMessage.create(chatData)
	}

	async rollResolveMod(actor, dataset) {
		const config = CONFIG.ALIENRPG
		const content = await foundry.applications.handlebars.renderTemplate(
			"systems/alienrpg/templates/dialog/roll-resolve-dialog.hbs",
			actor,
			dataset.dataset,
		)
		let response = ""
		const title =
			game.i18n.localize("ALIENRPG.DialTitle1") + " " + dataset.label + " " + game.i18n.localize("ALIENRPG.DialTitle2")
		let resolveMod = 0
		response = await foundry.applications.api.DialogV2.wait({
			window: { title: title },
			content,
			rejectClose: false,
			buttons: [
				{
					label: "ALIENRPG.DialRoll",
					callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
				},
				{
					label: "ALIENRPG.DialCancel",
					action: "cancel",
				},
			],
		})
		if (!response || response === "cancel") return "cancelled"
		if (response) {
			if (!response.resolveMod) {
				resolveMod = 0
			} else resolveMod = Number(response.resolveMod)
			if (Number.isNaN(response.resolveMod)) resolveMod = 0
			dataset.resolveMod = resolveMod
			this.rollResolve(actor, dataset)
		}
	}
	async rollStress(actor, dataset) {
		const config = CONFIG.ALIENRPG
		let htmlData = ""
		let aStress = 0
		const resolve = actor.getRollData().header.resolve.value
		const stressMod = Number(dataset?.stressMod ?? 0)
		const table = game.tables.getName("Panic Response Table")
		let status = ""
		let effectid = ""
		const oldPanic = actor.getRollData().general.panic.lastRoll
		let customResults = ""
		let altDescription = ""
		let roll = ""

		if (!table) {
			return ui.notifications.error(game.i18n.localize("ALIENRPG.NoResolveTable"))
		}

		// const stressModifier = Number(resolve) + Number(stressMod)

		if (actor.type === "synthetic") {
			if (!actor.system.header.synthstress) return
			aStress = 0
		} else {
			aStress = actor.getRollData().header.stress.value + Number(stressMod)
		}
		// roll = await new Roll(`(1d6) + (${aStress}-${resolve})`).evaluate()
		roll = await new Roll(`(1d6)`).evaluate()
		let rollTotal = roll.total + (aStress - resolve)
		
		console.warn(
			`Rolling Stress, ${roll}, Dice Value, ${roll.total},  Stress Value ${actor.system.header.stress.value}, Resolve Value ${resolve}, Current level ${oldPanic}, Total Roll ${rollTotal}`,
		)

		if (rollTotal < 0) {
			console.log("Can't go Lower than 0")
			rollTotal = 0
		} else {
	if (rollTotal >= 12 || oldPanic >= 12) {
			console.log("Can't go heigher than 12")
			rollTotal = 12
		}
	}

		if (rollTotal <= oldPanic) {
			console.log("you already have condition =>: ", rollTotal, "existing level: ", oldPanic)
			rollTotal = oldPanic + 1
		} 


		customResults = await table.getResultsForRoll(rollTotal)

		altDescription = customResults[0].description
		switch (rollTotal) {
			case 0:
				break
			case 1:
				{
					effectid = "spooked"
					if (await this.hasCondition(effectid)) {
					} else {
						await actor.update({
							"system.header.stress.value": actor.system.header.stress.value + 1,
						})
						status = effectid
					}
				}
				break
			case 2:
				{
					effectid = "noisy"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 3:
				{
					effectid = "twitchy"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 4:
				{
					effectid = "loseitem"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 5:
				{
					effectid = "paranoid"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 6:
				{
					effectid = "hesitant"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 7:
				{
					effectid = "freeze"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 8:
				{
					effectid = "seekcover"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 9:
				{
					effectid = "scream"
					if (await this.hasCondition(effectid)) {
					} else {
						await actor.update({
								"system.header.stress.value": actor.system.header.stress.value - 1,
							})
						status = effectid
					}
				}
				break
			case 10:
				{
					effectid = "flee"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			case 11:
				{
					effectid = "frenzy"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
			default:
				{
					effectid = "catatonic"
					if (await this.hasCondition(effectid)) {
					} else {
						status = effectid
					}
				}
				break
		}

		if (status) {
			await this.toggleStatusEffect(status)
			await actor.update({
			"system.general.panic.lastRoll": rollTotal,
		})
	}

		htmlData = {
			actorname: actor.name,
			img: customResults[0].img,
			name: customResults[0].name,
			description: altDescription,
			resolve: resolve,
			modifier: stressMod,
			result: rollTotal,
		}

		const html = await foundry.applications.handlebars.renderTemplate(
			"systems/alienrpg/templates/chat/panic-response-roll.hbs",
			htmlData,
		)
		const chatData = {
			user: game.user.id,
			speaker: {
				actor: actor.id,
			},
			content: html,
			other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
			sound: CONFIG.sounds.dice,
		}

		ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"))
		return ChatMessage.create(chatData)
		// }
	}

	async rollStressMod(actor, dataset) {
		const config = CONFIG.ALIENRPG
		const content = await foundry.applications.handlebars.renderTemplate(
			"systems/alienrpg/templates/dialog/roll-stress-dialog.hbs",
			actor,
			dataset.dataset,
		)
		let response = ""
		const title =
			game.i18n.localize("ALIENRPG.DialTitle1") + " " + dataset.label + " " + game.i18n.localize("ALIENRPG.DialTitle2")
		let stressMod = 0
		response = await foundry.applications.api.DialogV2.wait({
			window: { title: title },
			content,
			rejectClose: false,
			buttons: [
				{
					label: "ALIENRPG.DialRoll",
					callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
				},
				{
					label: "ALIENRPG.DialCancel",
					action: "cancel",
				},
			],
		})
		if (!response || response === "cancel") return "cancelled"
		if (response) {
			if (!response.stressMod) {
				stressMod = 0
			} else stressMod = Number(response.stressMod)
			if (Number.isNaN(response.stressMod)) stressMod = 0
			dataset.stressMod = stressMod
			this.rollStress(actor, dataset)
		}
	}

	async pushRoll(actor, reRoll, hostile, blind, message) {
		if (!game.settings.get("alienrpg", "evolved")) {
			await actor.update({
				"system.header.stress.value": actor.system.header.stress.value + 1,
			})
		} else {
			const addPanic = actor.getRollData().general.addpanic.value
			await actor.update({
				"system.header.stress.value": actor.system.header.stress.value + addPanic,
			})
		}
		const reRoll1 = game.alienrpg.rollArr.r1Dice - game.alienrpg.rollArr.r1Six
		const reRoll2 = game.alienrpg.rollArr.r2Dice + 1 - (game.alienrpg.rollArr.r2One + game.alienrpg.rollArr.r2Six)
		await yze.yzeRoll(
			hostile,
			blind,
			reRoll,
			game.alienrpg.rollArr.tLabel,
			reRoll1,
			game.i18n.localize("ALIENRPG.Black"),
			reRoll2,
			game.i18n.localize("ALIENRPG.Yellow"),
			actor.id,
			0,
			message.flags.tactorid,
		)
	}

	async rollItem(event) {
		event.preventDefault()
		const element = event.currentTarget
		const dataset = element.dataset
		const itemId = $(event.currentTarget).parents(".item").attr("data-item-id")
		const item = this.actor.items.get(itemId)
		if (item.type === "armor") {
			dataset.roll = this.actor.system.general.armor.value
			dataset.mod = 0
			dataset.spbutt = "armor"
			this.actor.rollAbility(this.actor, dataset)
		} else {
			// this.actor.nowRollItem(item);
			if (item.type === "weapon" || item.type === "spacecraftweapons") {
				// Trigger the item roll
				return item.roll(false)
			}
		}
	}
	async RollItemMod(event) {
		event.preventDefault()
		const element = event.currentTarget
		const dataset = element.dataset
		const itemId = $(event.currentTarget).parents(".item").attr("data-item-id")
		const item = this.actor.items.get(itemId)
		if (item.type === "armor") {
			dataset.roll = this.actor.system.general.armor.value
			dataset.mod = 0
			dataset.spbutt = "armor"
			this.actor.rollAbilityMod(this.actor, dataset)
		} else {
			// this.actor.rollItemMod(item);
			if (item.type === "weapon") {
				// Trigger the item roll
				return item.roll(true)
			}
		}
	}
	async addCondition(effect) {
		if (typeof effect === "string") {
			effect = foundry.utils.duplicate(game.alienrpg.config.conditionEffects.find((e) => e.id === effect))
		}
		if (!effect) return "No Effect Found"
		if (!effect.id) return "Conditions require an id field"

		const existing = await this.hasCondition(effect.id)

		if (!existing) {
			// if (game.version < '11') {
			effect.label = game.i18n.localize(effect.label).replace(/(^\w{1})|(\s+\w{1})/g, (letter) => letter.toUpperCase())
			effect.name = game.i18n.localize(effect.name).replace(/(^\w{1})|(\s+\w{1})/g, (letter) => letter.toUpperCase())
			// effect['flags.core.statusId'] = effect.id;
			effect["statuses"] = effect.id
			delete effect.id
			return await this.createEmbeddedDocuments("ActiveEffect", [effect])
		}
	}
	async removeCondition(effect) {
		if (typeof effect === "string") {
			effect = foundry.utils.duplicate(game.alienrpg.config.conditionEffects.find((e) => e.id === effect))
		}
		if (!effect) return "No Effect Found"
		if (!effect.id) return "Conditions require an id field"
		const existing = await this.hasCondition(effect.id)
		if (existing) {
			return await this.deleteEmbeddedDocuments("ActiveEffect", [existing._id])
		}
	}

	async hasCondition(conditionKey) {
		let existing = ""
		existing = this.effects.find((effect) => effect.statuses.has(conditionKey))
		return existing
	}

	async stressChange(actor, dataset) {
		switch (dataset.pmbut) {
			case "minusStress":
				if (actor.system.header.stress.value <= 0) {
					await actor.update({
						"system.header.stress.value": (actor.system.header.stress.value = 0),
					})
				} else {
					await actor.update({
						"system.header.stress.value": actor.system.header.stress.value - 1,
					})
				}
				break
			case "plusStress":
				await actor.update({
					"system.header.stress.value": actor.system.header.stress.value + 1,
				})
				break
			case "minusHealth":
				if (actor.system.header.health.value <= 0) {
					await actor.update({
						"system.header.health.value": (actor.system.header.health.value = 0),
					})
				} else {
					await actor.update({
						"system.header.health.value": actor.system.header.health.value - 1,
					})
				}
				break
			case "plusHealth":
				await actor.update({
					"system.header.health.value": actor.system.header.health.value + 1,
				})
				break

			default:
				break
		}
	}
	async ClickXPStatLevel(actor, button) {
		const xp = actor.system.general.xp
		if (button === 2) {
			// left click
			if (xp.value > 0) {
				if (xp.value === 0) {
					return
				}
				return await actor.update({
					["system.general.xp.value"]: xp.value - 1,
				})
			}
		} else {
			// right click
			if (xp.value < xp.max) {
				if (xp.value >= 25) {
					return
				}
				return await actor.update({
					["system.general.xp.value"]: xp.value + 1,
				})
			}
		}
	}
	async ClickSPStatLevel(actor, button) {
		const sp = actor.system.general.sp
		if (button === 2) {
			// left click
			if (sp.value > 0) {
				if (sp.value === 0) {
					return
				}
				return await actor.update({
					["system.general.sp.value"]: sp.value - 1,
				})
			}
		} else {
			// right click
			if (sp.value < sp.max) {
				if (sp.value >= 3) {
					return
				}
				return await actor.update({
					["system.general.sp.value"]: sp.value + 1,
				})
			}
		}
	}
	async ClickDamageLevel(actor, button) {
		let damage = actor.system.attributes.damage
		if (button === 2) {
			// left click
			if (damage.value > 0) {
				if (damage.value === 0) {
					return
				}
				return await actor.update({ ["system.attributes.damage.value"]: damage.value - 1 })
			}
		} else {
			// right click
			if (damage.value < damage.max) {
				if (damage.value >= 20) {
					return
				}
				return await actor.update({ ["system.attributes.damage.value"]: damage.value + 1 })
			}
		}
	}

	async reduceRadiation(actor, dataset) {
		const rad = actor.system.general.radiation
		const label = game.i18n.localize("ALIENRPG.RadiationReduced")
		const r1Data = 0
		const reRoll = true
		const actorId = actor.id
		const effectiveActorType = actor.type
		const blind = false
		const r2Data = 1
		const radMax = actor.getRollData().general.radiation.max
						if (!game.settings.get("alienrpg", "evolved")) {
		await yze.yzeRoll(
			effectiveActorType,
			blind,
			reRoll,
			label,
			r1Data,
			game.i18n.localize("ALIENRPG.Black"),
			r2Data,
			game.i18n.localize("ALIENRPG.Yellow"),
			actorId,
		)
		if (game.alienrpg.rollArr.r2One === 1) {
			await actor.update({
				"system.general.radiation.permanent": rad.permanent + 1,
				"system.RADfill": actor.system.RADfill + 1,
				"system.RADlost": actor.system.RADlost - 1,
				"system.general.radiation.value": rad.value - 1,
			})
		} else {
			await actor.update({ ["system.general.radiation.value"]: rad.value - 1 })
		} 
	}
		else 
			{
						await actor.update({ ["system.general.radiation.value"]: rad.value - 1 })
								ChatMessage.create({
			speaker: { actor: actor.id },
			content: game.i18n.localize("ALIENRPG.RadiationReduced"),
			type: CONST.CHAT_MESSAGE_STYLES.OTHER,
		})
}			
	}

	async _onOverwatchToggle(event) {
		const key = $(event.currentTarget).parents(".condition").attr("data-key")
		if (key === "overwatch") {
			if (await this.actor.hasCondition(key)) await this.actor.removeCondition(key)
			else await this.actor.addCondition(key)
		} else {
			if (event.type === "click") {
				if (!(await this.actor.hasCondition(key))) await this.actor.addCondition(key)
			} else {
				if (key === "panicked") {
					if (await this.actor.hasCondition(key)) await this.actor.checkAndEndPanic(this.actor)
				} else {
					if (await this.actor.hasCondition(key)) await this.actor.removeCondition(key)
				}
			}
		}
	}
	async checkAndEndPanic(actor) {
		let itemDel = ""
		const agilityModName =
			game.i18n.localize("ALIENRPG.PanicCondition") + " - " + game.i18n.localize("ALIENRPG.AbilityAgl") + " -2"
		const allSkillsModName =
			game.i18n.localize("ALIENRPG.PanicCondition") +
			" - " +
			game.i18n.localize("ALIENRPG.TREMBLE") +
			" -2 " +
			game.i18n.localize("ALIENRPG.Skills")

		if (actor.type !== "character") return

		if (actor.system.general.panic.lastRoll > 0) {
			await actor.update({
				"system.general.panic.value": 0,
				"system.general.panic.lastRoll": -1,
			})
		}
		await actor.removeCondition("panicked")
		ChatMessage.create({
			speaker: { actor: actor.id },
			content: "Panic is over",
			type: CONST.CHAT_MESSAGE_STYLES.OTHER,
		})
		itemDel = actor.items.getName(agilityModName)
		if (itemDel) {
			itemDel.delete()
		}
		itemDel = actor.items.getName(allSkillsModName)
		if (itemDel) {
			itemDel.delete()
		}
	}
	async causePanic(actor) {
		// await actor.update({ 'system.general.panic.value': 1 });
		await actor.addCondition("panicked")
		return
	}
	async rollCrit(actor, type, dataset, manCrit) {
		const config = CONFIG.ALIENRPG
		let atable = ""
		let healTime = 0
		let cFatal = false
		let factorFour = ""
		let testArray = ""
		let rollheal = ""
		let newHealTime = ""
		let htmlData = ""
		let resultImage = ""
		let shipcritTable = ""
		let test1 = ""
		let hFatal = ""
		let hHealTime = ""
		let hTimeLimit = ""
		let shipCritType = ""
		let mobility = 0
		let rangedcombat = 0
		let observation = 0
		let manipulation = 0
		let closecombat = 0
		let stamina = 0
		let comtech = 0
		let command = 0
		switch (type) {
			case "character":
{			
							if (game.settings.get("alienrpg", "evolved")) {
			atable =
					game.tables.getName(game.i18n.localize("ALIENRPG.EVCriticalInjuries")) ||
					game.tables.getName("EV - Critical Injuries")
						} else {
			atable =
					game.tables.getName(game.i18n.localize("ALIENRPG.CriticalInjuries")) ||
					game.tables.getName("Critical Injuries") ||
					game.tables.getName("Critical injuries")
				}
			}
			if (atable === null || atable === undefined) {
				ui.notifications.warn(game.i18n.localize("ALIENRPG.NoCharCrit"))
				return
			}							
						break
				case "synthetic":
// {		
// 			if (game.settings.get("alienrpg", "evolved")) {


// } else {
				atable =
					game.tables.getName("Critical Injuries on Synthetics") ||
					game.tables.getName("critical injuries on synthetics")
				if (atable === null || atable === undefined) {
					ui.notifications.warn(game.i18n.localize("ALIENRPG.NoSynCrit"))
					return
				}
			// }
		// }
				break
			case "creature":
				atable = game.tables.getName(dataset.atttype)
				if (atable === null || atable === undefined) {
					ui.notifications.warn(game.i18n.localize("ALIENRPG.NoCharCrit"))
					return
				}
				break

			case "spacecraft":
				if (dataset.crbut === "minor") {
					atable = game.tables.getName("Spaceship Minor Component Damage")
					shipcritTable = "0"
					if (atable === null || atable === undefined) {
						ui.notifications.warn(game.i18n.localize("ALIENRPG.NoCharCrit"))
						return
					}
				} else {
					atable = game.tables.getName("Spaceship Major Component Damage")
					shipcritTable = "1"
					if (atable === null || atable === undefined) {
						ui.notifications.warn(game.i18n.localize("ALIENRPG.NoCharCrit"))
						return
					}
				}
				break

			default:
				return
		}

		if (!manCrit) {
			test1 = await atable.draw({ displayChat: false })
		} else {
			const formula = manCrit
			const roll = await new Roll(formula).evaluate()
			test1 = await atable.draw({ roll: roll, displayChat: false })
		}
		const messG = test1.results[0].description
		switch (type) {
			case "character":
				{
					resultImage = test1.results[0].img
					factorFour = messG.replace(/(<b>)|(<p>|)(<strong>)|(<\/b>)|(<\/p>)|(<\/strong>)/gi, "")
					testArray = factorFour.split(/[:] |<br \/>/gi)
					let speanex = testArray[7]
					if (testArray[9] !== game.i18n.localize("ALIENRPG.Permanent")) {
						if (testArray[9].length > 0) {
						if (testArray[9]=== 'Shift') {
							testArray[9] = game.i18n.localize("ALIENRPG.Shift")
						} else {
							rollheal = testArray[9].match(/^\[\[([0-9]d[0-9]+)]/)[1]
							newHealTime = testArray[9].match(/^\[\[([0-9]d[0-9]+)\]\] ?(.*)/)[2]
							testArray[9] = (await new Roll(`${rollheal}`).evaluate()).result + " " + newHealTime
							// testArray[9] = (await new Roll(`${rollheal}`).evaluate().result) + ' ' + newHealTime;
						}
						} else {
							testArray[9] = game.i18n.localize("ALIENRPG.None")
						}
					}
					switch (testArray[3]) {
						case game.i18n.localize("ALIENRPG.Yes") + " ":
							cFatal = true
							break
						case game.i18n.localize("ALIENRPG.Yes") + ", –1 ":
							{
								cFatal = true
								speanex += "<br> -1 to <strong>" + game.i18n.localize("ALIENRPG.SkillmedicalAid") + "</strong> roll"
							}
							break
						case game.i18n.localize("ALIENRPG.Yes") + ", –2 ":
							{
								cFatal = true
								speanex += "<br> -2 to <strong>" + game.i18n.localize("ALIENRPG.SkillmedicalAid") + "</strong> roll"
							}
							break
						default:
							cFatal = false
							break
					}

					switch (testArray[5]) {
						case game.i18n.localize("ALIENRPG.None") + " ":
							healTime = 0
							break
						case game.i18n.localize("ALIENRPG.OneRound") + " ":
							healTime = 1
							break
						case game.i18n.localize("ALIENRPG.OneTurn") + " ":
							healTime = 2
							break
						case game.i18n.localize("ALIENRPG.OneShift") + " ":
							healTime = 3
							break
						case game.i18n.localize("ALIENRPG.OneDay") + " ":
							healTime = 4
							break
						default:
							healTime = 0
							break
					}
							if (game.settings.get("alienrpg", "evolved")) {
					switch (test1.roll._total) {
						case 15:
							rangedcombat = -1
							observation = -1
							break
						case 16:
							observation = -1
							comtech = -1
							break
						case 21:
							observation = -2
							break
						case 24:
							manipulation = -2
							break
						case 31:
							observation = -1
							manipulation = -1
							break
						case 32:
							mobility = -2
							closecombat = -2
							break
						case 33:
							rangedcombat = -2
							observation = -2
							break
						case 34:
							manipulation = -2
							command = -2
							break
						case 42:
							manipulation = -2
							break
						case 44:
							mobility = -2
							closecombat = -2
							break
						case 51:
							observation = -2
							comtech = -2
							break
						case 61:
							stamina = -1
							break
						case 62:
							stamina = -2
							break
						case 62:
							stamina = -3
							break

						default:
							break
					}
							} else
								{
					switch (test1.roll._total) {
						case 14:
							mobility = -2
							break
						case 15:
							rangedcombat = -2
							observation = -2
							break
						case 16:
							mobility = -2
							break
						case 21:
							observation = -2
							break
						case 24:
							manipulation = -2
							break
						case 31:
							observation = -1
							manipulation = -1
							break
						case 33:
							mobility = -2
							closecombat = -2
							break
						case 34:
							rangedcombat = -2
							observation = -2
							break
						case 44:
							mobility = -2
							stamina = -2
							break
						case 51:
							mobility = -2
							break
						case 61:
							stamina = -1
							break
						case 62:
							stamina = -2
							break

						default:
							break
					}
				}
					//
					// Now create the item on the sheet
					//
					const rollData = {
						type: "critical-injury",
						img: resultImage,
						name: `#${test1.roll._total} ${testArray[1]}`,
						"system.header.active": true,
						"system.attributes.fatal": cFatal,
						"system.attributes.timelimit.value": healTime,
						"system.attributes.healingtime.value": testArray[9],
						"system.attributes.effects": speanex,
						"system.modifiers.skills.mobility.value": mobility,
						"system.modifiers.skills.rangedCbt.value": rangedcombat,
						"system.modifiers.skills.observation.value": observation,
						"system.modifiers.skills.manipulation.value": manipulation,
						"system.modifiers.skills.closeCbt.value": closecombat,
						"system.modifiers.skills.stamina.value": stamina,
						"system.modifiers.skills.comtech.value": comtech,
						"system.modifiers.skills.command.value": command,
					}

					await this.createEmbeddedDocuments("Item", [rollData])
					//
					// Prepare the data for the chat message
					//

					hFatal = testArray[3] !== " " ? testArray[3] : game.i18n.localize("ALIENRPG.None")
					hHealTime = testArray[9] !== " " ? testArray[9] : game.i18n.localize("ALIENRPG.None")
					hTimeLimit = testArray[5] !== " " ? testArray[5] : game.i18n.localize("ALIENRPG.None")

					htmlData = {
						actorname: actor.name,
						img: resultImage,
						name: `#${test1.roll._total} ${testArray[1]}`,
						fatal: hFatal,
						timelimit: hTimeLimit,
						healingtime: hHealTime,
						effects: speanex,
						manCrit: manCrit,
					}
				}

				break
			case "synthetic":
			case "creature":
				{
					resultImage = test1.results[0].img || "icons/svg/biohazard.svg"
					if (type === "creature") {
						resultImage = "icons/svg/biohazard.svg"
					}
					factorFour = messG.replace(/(<b>)|(<p>|)(<strong>)|(<\/b>)|(<\/p>)|(<\/strong>)/gi, "")

					// factorFour = messG.replace(/(<b>)|(<\/b>)/gi, '');
					testArray = factorFour.split(/[:] |<br \/>/gi)

					//
					// Now create the item on the sheet
					//
					await actor.createEmbeddedDocuments("Item", [
						{
							type: "critical-injury",
							img: resultImage,
							name: `#${test1.roll.total} ${testArray[0]}`,
							"system.attributes.effects": testArray[1],
						},
					])

					//
					// Prepare the data for the chat message
					//

					htmlData = {
						actorname: actor.name,
						img: resultImage,
						name: `#${test1.roll.total} ${testArray[0]}`,
						effects: testArray[1],
						manCrit: manCrit,
					}
				}
				break
			case "spacecraft":
				{
					resultImage = test1.results[0].img || "icons/svg/biohazard.svg"

					// factorFour = messG.replace(/(<strong>)|(<\/strong>)/gi, '');
					factorFour = messG.replace(/(<b>)|(<p>|)(<strong>)|(<\/b>)|(<\/p>)|(<\/strong>)/gi, "")
					testArray = factorFour.split(/[:] |<br \/>/gi)

					//
					// Now create the item on the sheet
					//
					await actor.createEmbeddedDocuments("Item", [
						{
							type: "spacecraft-crit",
							img: resultImage,
							name: `#${test1.roll.total} ${testArray[0]}`,
							"system.header.type.value": `${shipcritTable}`,
							"system.header.effects": testArray[2],
							"system.header.repairroll": testArray[5],
						},
					])

					//
					// Prepare the data for the chat message
					//
					if (shipcritTable === "0") {
						shipCritType = "Minor"
					} else {
						shipCritType = "Major"
					}
					htmlData = {
						shipCritType: `${shipCritType}`,
						actorname: actor.name,
						img: resultImage,
						name: `#${test1.roll.total} ${testArray[0]}`,
						ceffects: testArray[2],
						crepairroll: testArray[5],
					}
				}
				break
		}

		// Now push the correct chat message

		// console.log(htmlData);
		const html = await foundry.applications.handlebars.renderTemplate(
			`systems/alienrpg/templates/chat/crit-roll-${actor.type}.hbs`,
			htmlData,
		)
		const chatData = {
			user: game.user.id,
			speaker: {
				actor: actor.id,
			},
			content: html,
			other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
			sound: CONFIG.sounds.dice,
		}

		switch (type) {
			case "spacecraft":
				if (shipCritType === "Minor") {
					await this.addCondition("shipminor")
				} else {
					await this.addCondition("shipmajor")
				}
				break
			case "character":
			case "synthetic":
				await this.addCondition("criticalinj")
				break
			case "creature":
				console.log("it's a Creature Crit")
				break

			default:
				break
		}

		ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"))
		return ChatMessage.create(chatData)
	}
	async rollCritMan(actor, type, dataset) {
		const config = CONFIG.ALIENRPG
		let content = ""
		let response = ""
		const title = game.i18n.localize("ALIENRPG.RollManCrit")
		let manCrit = 0
		switch (actor.type) {
			case "character":
				{
					content = await foundry.applications.handlebars.renderTemplate(
						"systems/alienrpg/templates/dialog/roll-char-manual-crit-dialog.hbs",
						actor,
						dataset.dataset,
					)
				}
				break
			case "synthetic":
			case "creature":
				{
					content = await foundry.applications.handlebars.renderTemplate(
						"systems/alienrpg/templates/dialog//roll-syn-manual-crit-dialog.hbs",
						actor,
						dataset.dataset,
					)
				}
				break
			case "spacecraft":
				{
					if (dataset.crbut === "minor") {
						content = await foundry.applications.handlebars.renderTemplate(
							"systems/alienrpg/templates/dialog/roll-spacecraft-minor-crit-dialog.hbs",
							actor,
							dataset.dataset,
						)
					} else {
						content = await foundry.applications.handlebars.renderTemplate(
							"systems/alienrpg/templates/roll-spacecraft-major-crit-dialog.hbs",
							actor,
							dataset.dataset,
						)
					}
				}

				break

			default:
				break
		}
		response = await foundry.applications.api.DialogV2.wait({
			window: { title: title },
			content,
			rejectClose: false,
			buttons: [
				{
					label: "ALIENRPG.DialRoll",
					callback: (event, button) => new foundry.applications.ux.FormDataExtended(button.form).object,
				},
				{
					label: "ALIENRPG.DialCancel",
					action: "cancel",
				},
			],
		})

		if (!response || response === "cancel") return "cancelled"
		if (response) {
			if (response.manCrit === "undefined") {
				manCrit = 0
			} else manCrit = response.manCrit
			switch (type) {
				case "synthetic":
					if (manCrit > 6) {
						ui.notifications.warn(game.i18n.localize("ALIENRPG.RollManSynCrit"))
						return
					}
					break
				case "character":
					if (!manCrit.match(/^[1-6]?[1-6]$/gm)) {
						ui.notifications.warn(game.i18n.localize("ALIENRPG.RollManCharCrit"))
						return
					}
					break
				case "spacecraft":
					if (dataset.crbut === "minor") {
						if (!manCrit.match(/^[1-66]?[1-66]$/gm)) {
							ui.notifications.warn(game.i18n.localize("ALIENRPG.RollManShipMinorCrit"))
							return
						}
					} else {
						if (dataset.crbut === "major") {
							if (!manCrit.match(/^[1-12]?[1-12]$/gm)) {
								ui.notifications.warn(game.i18n.localize("ALIENRPG.RollManShipMajorCrit"))
								return
							}
						}
					}
					break
				default:
					break
			}
			actor.rollCrit(actor, type, dataset, manCrit)
		}
	}
	async createChatMessage(message, actorID) {
		const config = CONFIG.ALIENRPG
		const chatData = {
			user: game.user.id,
			speaker: {
				actor: actorID,
			},
			content: new Handlebars.SafeString(message),
			other: game.users.contents.filter((u) => u.isGM).map((u) => u.id),
			sound: CONFIG.sounds.lock,
		}

		ChatMessage.applyRollMode(chatData, game.settings.get("core", "rollMode"))
		return ChatMessage.create(chatData)
	}

	/**
	 * Toggle a configured status effect for the Actor.
	 * @param {string} statusId       A status effect ID defined in CONFIG.statusEffects.
	 * @param {object} [options={}]   Additional options which modify how the effect is created.
	 * @param {boolean} [options.active]          Force the effect to be active or inactive regardless of its current state.
	 * @param {boolean} [options.overlay=false]   Display the toggled effect as an overlay.
	 * @param {string} [options.effectEnd]        Value for `system.end.type`.
	 * @returns {PromiseAlienRPGActiveEffect|boolean|undefined>}  A promise which resolves to one of the following values:
	 *                                 - ActiveEffect if a new effect need to be created
	 *                                 - true if was already an existing effect
	 *                                 - false if an existing effect needed to be removed
	 *                                 - undefined if no changes need to be made.
	 * @override Implementation copied from core.
	 */
	async toggleStatusEffect(statusId, { active, overlay = false, effectEnd = "" } = {}) {
		const status = CONFIG.statusEffects.find((e) => e.id === statusId)
		if (!status) throw new Error(`Invalid status ID "${statusId}" provided to Actor#toggleStatusEffect`)
		const existing = []
		const hitList = []
		// const lastRoll = this.system.general.panic.lastRoll

		// Find the effect with the static _id of the status effect
		if (status._id) {
			const effect = this.effects.get(status._id)
			if (effect) existing.push(effect.id)
		}
		// If no static _id, find all single-status effects that have this status
		else {
			for (const effect of this.effects) {
				const statuses = effect.statuses
				if (statuses.size === 1 && statuses.has(status.id)) existing.push(effect.id)
			}
		}

		// Remove the existing effects unless the status effect is forced active
		if (existing.length) {
			if (active) return true
			await this.deleteEmbeddedDocuments("ActiveEffect", existing)
			for (const effect of this.effects) {
				for (const effectList of CONFIG.statusEffects) {
					if (effectList.id === effect.name.toLowerCase()) {
						hitList.push(effectList.tableNumber)
					}
				}
			}
			hitList.sort().reverse()
			await this.update({ "system.general.panic.lastRoll": hitList[0] })
			if (hitList.length === 0) {
				if (status.resp === 'panic'){
				await this.update({ "system.general.panic.lastRoll": -1 })
				} else {
					await this.update({ "system.general.stressresponse.value": -1 })
				}
			}
			return false
		}

		// Create a new effect unless the status effect is forced inactive
		if (!active && active !== undefined) return
		const effect = await AlienRPGActiveEffect.fromStatusEffect(statusId)
		if (overlay) effect.updateSource({ "flags.core.overlay": true })
		if (effectEnd) effect.updateSource({ "system.end.type": effectEnd })
			if (this.type === "character") {

				if (status.resp === 'panic'){
				if (status.tableNumber > this.system.general.panic.lastRoll) {
					await this.update({ "system.general.panic.lastRoll": status.tableNumber })
				}
			} else {
								if (status.tableNumber > this.system.general.stressresponse.value) {
					await this.update({ "system.general.stressresponse.value": status.tableNumber })
				}
			}

				
			} 
		return AlienRPGActiveEffect.create(effect, { parent: this, keepId: true })
	}
	/* ------------------------------------------- */
	/*  Vehicle: Crew Management                   */
	/* ------------------------------------------- */

	/**
	 * Adds an occupant to the vehicle.
	 * @param {string}  crewId              The id of the added actor
	 * @param {string}  [position='PASSENGER'] Crew position flag ('PASSENGER', 'DRIVER', 'GUNNER', or 'COMMANDER')
	 * @param {boolean} [isExposed=false]   Whether it's an exposed position
	 * @returns {VehicleOccupant}
	 */
	async addVehicleOccupant(crewId, position = "PASSENGER") {
		if (this.type !== "vehicles" && this.type !== "spacecraft") return
		if (this.type === "vehicles") {
			if (!CONFIG.ALIENRPG.vehicle.crewPositionFlags.includes(position)) {
				throw new TypeError(`alienrpg | addVehicleOccupant | Wrong position flag: ${position}`)
			}
		} else if (this.type === "spacecraft") {
			// position = 'CREW';
			if (!CONFIG.ALIENRPG.spacecraft.crewPositionFlags.includes(position)) {
				throw new TypeError(`alienrpg | addVehicleOccupant | Wrong position flag: ${position}`)
			}
		}
		const system = this.system
		// if (!(system.crew.occupants instanceof Array)) {
		//   system.crew.occupants = [];
		// }
		const occupant = {
			id: crewId,
			position,
		}
		// Removes duplicates.
		if (system.crew.occupants.some((o) => o.id === crewId)) this.removeVehicleOccupant(crewId)
		// Adds the new occupant.
		system.crew.occupants.push(occupant)
		await this.update({ "system.crew.occupants": system.crew.occupants })

		await this.update({ "system.crew.passengerQty": system.crew.occupants.length })

		return occupant
	}
	/* ------------------------------------------- */

	/**
	 * Removes an occupant from the vehicle.
	 * @param {string} crewId The id of the occupant to remove
	 * @return {VehicleOccupant[]}
	 */
	removeVehicleOccupant(crewId) {
		if (this.type !== "vehicles" && this.type !== "spacecraft") return
		const crew = this.system.crew
		crew.occupants = crew.occupants.filter((o) => o.id !== crewId)
		return crew.occupants
	}

	/* ------------------------------------------- */

	/**
	 * Gets a specific occupant in the vehicle.
	 * @param {string} crewId The id of the occupant to find
	 * @returns {VehicleOccupant|undefined}
	 */
	getVehicleOccupant(crewId) {
		if (this.type !== "vehicles" && this.type !== "spacecraft") return
		return this.system.crew.occupants.find((o) => o.id === crewId)
	}

	/* ------------------------------------------- */

	/**
	 * Gets a collection of crewed actors.
	 * @returns {Collection<string, Actor>} [id, actor]
	 */
	getCrew() {
		if (this.type !== "vehicles" && this.type !== "spacecraft") return undefined
		const c = new foundry.utils.Collection()
		for (const o of this.system.crew.occupants) {
			c.set(o.id, game.actors.get(o.id))
		}
		return c
	}
}
